on:
  pull_request:
    branches:
      - main
    types: ["closed"]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  id-token: write

jobs:
  cherry_pick_release_1_27:
    runs-on: ubuntu-latest
    name: cherry pick into release-1.27
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cherry pick into release-1.27
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          token: ${{ github.token }}
          branch: release-1.27
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'
          labels: |
            cherry-pick
